# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './data_ombu_mariadb:/var/lib/mysql'

  moodle:
    image: docker.io/bitnami/moodle:4.3
    environment:
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - BITNAMI_DEBUG=true
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_HOST=espacioombu.local
      - MOODLE_LANG=es
      - MOODLE_SMTP_HOST=${SMTP_HOST}
      - MOODLE_SMTP_PORT=${SMTP_PORT}
      - MOODLE_SMTP_USER=${SMTP_USER}
      - MOODLE_SMTP_PASSWORD=${SMTP_PASSWORD}
      - MOODLE_SMTP_PROTOCOL=${SMTP_PROTOCOL}

    volumes:
      - './data_ombu_moodle:/bitnami/moodle'
      - './data_ombu_moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle-ombu.rule=Host(`${DOMINIO:?DOMINIO variable is not set}`)"
      - "traefik.http.routers.moodle-ombu.entrypoints=websecure"
      - "traefik.http.routers.moodle-ombu.tls.certresolver=myresolver"

