# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  grafana:
    image: grafana/grafana:6.7.3
    container_name: grafana
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${DOMINIO}`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.middlewares=grafana-stripprefix"
      - "traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana"
    volumes:
      - "grafana:/var/lib/grafana"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus:/prometheus"


  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - moodle

  moodle:
    image: docker.io/bitnami/moodle:4.3
    environment:
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - BITNAMI_DEBUG=true
      - MOODLE_HOST=${DOMINIO}
      - MOODLE_REVERSEPROXY=true
      - MOODLE_SSLPROXY=true
      - MOODLE_LANG=es
    volumes:
      - './data_ombu_moodle:/bitnami/moodle'
      - './data_ombu_moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle-ombu.rule=Host(`${DOMINIO:?DOMINIO variable is not set}`)"
      - "traefik.http.routers.moodle-ombu.entrypoints=websecure"
      - "traefik.http.routers.moodle-ombu.tls.certresolver=myresolver"
    networks:
      - moodle

networks:
  moodle:
    name: moodle_network      
volumes:
    mariadb_data:
      driver: local
    grafana:
      driver: local
  # moodle_data:
  #   driver: local
  # moodledata_data:
  #   driver: local
