global:
  external_labels:
    monitor: 'utils-monitor'
    
scrape_configs:
  - job_name: 'traefik'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - traefik:8080
