## traefik.yml

# Docker configuration backend
providers:
  docker:
    exposedByDefault: true

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: false
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "contacto@espacioombu.cl"
      storage: "/letsencrypt/acme.json"
      tlsChallenge: {}




